### ISSUE TITLE
pook.use() context manager is stilll active after use even in follow-up testcases

### ISSUE THREAD

**Issue by MoleMan1024** [h2non/pook#72] opened 2020-08-21 11:47 UTC
Hi,
thanks for pook, it's a very handy library that I use in my pytest tests.

However I think I found a bug (using pook v1.0.1, Python 3.8.2, requests 2.21.0, Windows 10): 
When using _pook.use()_ as context manager to replace a _requests.get()_ call pook does not seem to remove the patching afterwards. It will also stay active across any follow-up testcases. I can reproduce it using the following pytest:

```
def test_pookUse_contextManager_isDisabledAfterUse():
    url = 'http://foo.bar'
    with pytest.raises(requests.exceptions.ConnectionError):
        requests.get(url)
    respJson = {"resp": "ok"}
    with pook.use():
        pook.get(url).reply().json(respJson)
        resp = requests.get(url)
        assert resp.json() == respJson
        assert pook.isdone()
    assert not pook.isactive()
    with pytest.raises(requests.exceptions.ConnectionError):
        requests.get(url)
```

Pytest output:

```
tests\integration\engines_test.py:14 (test_pookUse_contextManager_isDisabledAfterUse)
def test_pookUse_contextManager_isDisabledAfterUse():
        url = 'http://foo.bar'
        with pytest.raises(requests.exceptions.ConnectionError):
            requests.get(url)
        respJson = {"resp": "ok"}
        with pook.use():
            pook.get(url).reply().json(respJson)
            resp = requests.get(url)
            assert resp.json() == respJson
            assert pook.isdone()
        assert not pook.isactive()
        with pytest.raises(requests.exceptions.ConnectionError):
>           requests.get(url)

tests\integration\engines_test.py:27: 

[...]

            # Raise no matches exception
>           raise PookNoMatches(msg)
E           pook.exceptions.PookNoMatches: pook error!
E           
E           => Cannot match any mock for the following request:
E           ==================================================
E           Method: GET
E           URL: http://foo.bar:80/
E           Headers: HTTPHeaderDict({'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'})
E           ==================================================

pook\engine.py:443: PookNoMatches
```

I put the testcase as the first one that is executed in all modules to avoid any effects from previous testcases (I put it on top in _tests/integration/engines_test.py_ ).
I could not yet figure out what the issue is. Could you have a look if it is reproducible on your side as well? Thank you.

**Comment by libbkmz** [comment] 2021-02-26 22:44
I found this issue is very annoying when I have mixed tests with and without pook. I'm unable to run this code:
```
import unittest
import pook
import requests as req


class TestPookBug(unittest.TestCase):
    @pook.get("http://google.com", reply=201)
    def test_1_with_pook(self):
        self.assertEqual(req.get("http://google.com").status_code, 201)

    def test_2_no_pook(self):
        req.get("http://google.com")

```

When I run all tests, the first one is creating mocks and successfully passing the test, but the second test doesn't want to use any mocks but fails because some tests with pook created some interceptors before.

**Comment by libbkmz** [comment] 2021-02-27 01:03
I have this dirty hack for the issue:
```
diff --git a/pook/interceptors/urllib3.py b/pook/interceptors/urllib3.py
index 18247a4..0287768 100644
--- a/pook/interceptors/urllib3.py
+++ b/pook/interceptors/urllib3.py
@@ -26,6 +26,17 @@ PATCHES = (
     'urllib3.connectionpool.HTTPConnectionPool.urlopen'
 )
 
+import importlib
+s = set()
+for x in PATCHES:
+    module_path, module_class, module_fn = x.rsplit(".", 2)
+    s.add((importlib.import_module(module_path), module_class, module_fn))
+
+PATCHES = tuple((
+    "%s.%s.%s" % (module.__name__, module_class, module_fn) for module, module_class, module_fn in s
+))
+
+
 RESPONSE_CLASS = 'HTTPResponse'
 
 RESPONSE_PATH = {

```
But that is not the right way of doing things. `_patch` must be moved to the base interceptor and all patching must be done in one place by checking if we have already patched this method or not. I Will think about this way a bit more later

**Comment by pdecat** [comment] 2021-07-30 15:14
Resolved by https://github.com/h2non/pook/pull/68?

**Comment by sarayourfriend** [comment] 2023-12-31 22:23
I've tried reproducing this in https://github.com/h2non/pook/pull/108 but am unable to.

Run the test using `hatch run test_requests:test -k test_pook_use_context_manager_is_disabled_after_exit`.

I'm going to close this as fixed, but if anyone is able to reproduce this, please comment and I'll reopen it and find a fix.

**Closed by sarayourfriend** 2023-12-31 22:23 UTC
Labels: bug, enhancement
